### PR TITLE
Add SetSettings for settings not from flags

### PR DESCRIPTION
**Pull request by sergeylanzman**

### CODE REVIEW

**Comment by on99** [comment]
Awesome, exactly what I want for now.

**Comment by sergeylanzman** [comment]
This option is not mandatory. More useful and not complicate the code.

**Comment by sergeylanzman** [comment]
UP!

**Comment by rjrobinson** [comment]
Anyone keeping up with this project?

**Comment by benmanns** [comment]
Merging as-is, but I am going to update `Uri` to `URI` to match the Golint initialism rules.

**Pull request merged**
