### PR TITLE
Please make config variables public

### PR DESCRIPTION
**Pull request by xuxiangyang**
I have an idea that we could make the config variables could access  out of the package. so I could change the config I my golang project instead of using env.

### CODE REVIEW

**Comment by xuxiangyang** [comment]
and I have a question, how can I monitor the jobs? such as how many failed jobs and the error? Is there a web server? Or I only could use redis command?

**Comment by Aorioli** [comment]
For monitoring you can use https://github.com/resque/resque-web, but it requires additional setup/resources.

**Comment by xuxiangyang** [comment]
@Aorioli thx, could you give me some exmaples?

**Comment by Aorioli** [comment]
Not really :) Just follow the guide in the resque-web repo to set it up, and make sure it connects to the same Redis instance as goworker, and everything will work out of the box. Of course it helps if you know the ruby stuff they talk about, which if you don't can probably be covered by 1-2 hour intro to ruby/rails.

**Comment by xuxiangyang** [comment]
ok~thx

**Comment by benmanns** [comment]
Check the new SetSettings method that @sergeylanzman added in #38.

**Pull request closed without merging**
