### PR TITLE
Added function to Enqueue new jobs

### PR DESCRIPTION
**Pull request by tinygrasshopper**
Made Job public to support Enqueue with the interface

```go
Enqueue(&Job{
		Queue:"queueName",
		Payload: Payload{
			Class: "JobName",
			Args:  []interface{}{"params"},
		},
	})
```

### CODE REVIEW

**Comment by Funfun** [comment]
:+1:

**Comment by nonmadden** [comment]
:+1:

**Comment by simplyb** [comment]
:+1:

**Comment by cdrage** [comment]
ping @benmanns can we get this merged :)

**Comment by simplyb** [comment]
It's working well for me

**Comment by cdrage** [comment]
This (partly) fixes issue #1

**Comment by cthulhu** [comment]
Guys could you please accept this pull-request? It works for me as well.

**Comment by cdrage** [comment]
I believe the owner hasn't pulled anything in since June. We may have to
fork this repo if he doesn't show up / assign a co-owner/contributor.

**Comment by cdrage** [comment]
Timeout pinging @benmanns.. trying again!

**Comment by benmanns** [comment]
Sorry for the delay on this - it's my intention to get goworker set up in a more modular pattern, out of which we can get better connection management. However, I'm letting perfect be the enemy of good, so I think it's appropriate to merge now. If anyone would care to help with maintenance on this, I would be happy to grant access.

**Pull request merged**
